### ISSUE TITLE
No "weffles.csv" or "bookmarks.stream" in C:\WEFFLES

### ISSUE THREAD

**Issue by 7MinSec** [jepayneMSFT/WEFFLES#1]
*Hey I promise I'm not trying to nag (I sent you a tweet and also submitted a comment to the [TechNet article](https://blogs.technet.microsoft.com/jepayne/2017/12/08/weffles/) but figured that maybe here in the issues are would be the best place for it!  That way if it gets solved, everybody wins! :-)*

I followed the steps in the article and am at the point where my collector is definitely ingesting logs, however, I see no `C:\weffles\weffles.csv` or `c:\weffles\bookmarks.stream` files created.  Any idea as to what might be causing that?

Thanks,
Brian

**Comment by braimee** [comment]
Quick update - fixed it!  I manually ran the scheduled Powershell task on the collector and the output pointed to .NET 3.5 not being installed.  Installed it, rebooted the machine and now those files are created!  I think I'm good to go.

**Comment by braimee** [comment]
Hey @jepayneMSFT I also wrote out all the steps for install/config of WEFFLES as I followed your article.  It's here FYI: [http://bpatty.rocks/#!pentesting/blue_team/weffles.md](http://bpatty.rocks/#!pentesting/blue_team/weffles.md).

**Comment by jepayneMSFT** [comment]
This issue is usually solved by ensuring the scheduled task is running. You can manually start the scheduled task to test, check the Task Scheduler Operational Log for issues, or ensure you have a copy of PowerShell running as system as a test. If there is something such as an error preventing the task from running, it will show up in the Task Scheduler log. The documentation at https://aka.ms/weffles covers that there needs to be a reboot or a start of the task to get the file to be created, I would recommend anyone else with this issue check there.

**Comment by 7MinSec** [comment]
Hey Jessica, is .NET 3.5 required though?  I can go back and redo the setup in the lab, but I could've sworn that when I ran the scheduled task manually in PS console, it griped about some error pointing to .NET 3.5 missing.  I installed that, rebooted, and then things were good to go.  I had also rebooted previous to the .NET install multiple times.
